# Generated by Django 3.1.1 on 2020-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_fun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplelist',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
